# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          http://scottwilson46.github.io/poole/
author:
  name:           Scott Wilson

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/scottwilson46/scottwilson46.github.io
